/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package todolist.kotlin

import repository.TodoListRepositoryImpl
import services.TodoListServiceImpl
import view.TodoListView


fun main() {
    val todoListRepository = TodoListRepositoryImpl()
    val todoListService = TodoListServiceImpl(todoListRepository)
    val todoListView = TodoListView(todoListService)

    todoListView.showTodoList()

}
